
all:
	g++ -std=c++11 edgelist_to_binary.cpp -o edgelist_to_binary
	g++ -std=c++11 csc_to_binary.cpp -o csc_to_binary
	g++ -std=c++11 remove_dups.cpp -o remove_dups

clean:
	rm -f a.out *.bin num_nodes_edges.txt *~ edgelist_to_binary csc_to_binary remove_dups
